### ISSUE TITLE
members are not recognized for pfsense_interface_group module

### ISSUE THREAD

**Issue by loictlpk** [pfsensible/core#84] opened 2023-08-07 10:21 UTC
- info
My ssh connection is working for each other modules i use... 
- code
```
- name: add interface group
  pfsensible.core.pfsense_interface_group:
    name: test
    members:
      - lana
      - lanb
    descr: test
    state: present
```
- error
`[- ](fatal: [pfswitch]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 172.20.31.230 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1691403167.3101437-16829-183913792431140/AnsiballZ_pfsense_interface_group.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1691403167.3101437-16829-183913792431140/AnsiballZ_pfsense_interface_group.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1691403167.3101437-16829-183913792431140/AnsiballZ_pfsense_interface_group.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.pfsensible.core.plugins.modules.pfsense_interface_group', init_globals=dict(_module_fqn='ansible_collections.pfsensible.core.plugins.modules.pfsense_interface_group', _modlib_path=modlib_path),\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_interface_group_payload_xeru3ftw/ansible_pfsensible.core.pfsense_interface_group_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_interface_group.py\", line 93, in <module>\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_interface_group_payload_xeru3ftw/ansible_pfsensible.core.pfsense_interface_group_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_interface_group.py\", line 88, in main\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_interface_group_payload_xeru3ftw/ansible_pfsensible.core.pfsense_interface_group_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/module_base.py\", line 227, in run\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_interface_group_payload_xeru3ftw/ansible_pfsensible.core.pfsense_interface_group_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/interface_group.py\", line 113, in _find_target\r\nIndexError: list index out of range\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1})`

**Comment by opoplawski** [comment] 2023-12-23 01:56
This is a duplicate of #74

**Closed by opoplawski** 2023-12-23 01:56 UTC
